[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "/"

[build.environment]
  NODE_VERSION = ">=20.x"
  NPM_FLAGS = "--legacy-peer-deps"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  SHARP_DIST_BASE_URL = "https://npmmirror.com/mirrors/sharp/0.33.5/"
  CI = "false"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 3000
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:;"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), interest-cohort=()"
    Cache-Control = "public, max-age=0, must-revalidate"
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://yourwebsite.report-uri.com/a/d/g"}]}'

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["dist/**"]