[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "/"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NODE_VERSION = ">=20.x"
  NPM_FLAGS = "--legacy-peer-deps"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  SHARP_DIST_BASE_URL = "https://npmmirror.com/mirrors/sharp"
  CI = "false"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NETLIFY_USE_YARN = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  SHARP_LIBVIPS_VERSION = "8.14.3"

[build.processing]
  skip_processing = false
  css.bundle = true
  css.minify = true
  js.bundle = true
  js.minify = true
  images.compress = true

[build.processing.images]
  quality = 85
  formats = ["webp", "avif"]

[build.processing.html]
  pretty_urls = true
  link_masking = true

# Cache Control
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; img-src 'self' data: blob: https:; font-src 'self' data: https:; connect-src 'self' https:; media-src 'self' https:; object-src 'none'; frame-ancestors 'none';"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Production context with optimizations
[context.production]
  command = "npm ci && npm run build"
  publish = "dist"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "production"
    CI = "true"

# Deploy Preview optimizations
[context.deploy-preview]
  command = "npm ci && npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "preview"
    VITE_APP_ENV = "preview"
    CI = "true"

# Branch deploy optimizations
[context.branch-deploy]
  command = "npm ci && npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_APP_ENV = "development"

# Development optimization
[dev]
  framework = "vite"
  targetPort = 3000
  autoLaunch = true
  command = "npm run dev"

# Function optimization
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["dist/**"]
  directory = "netlify/functions"

# Plugins for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Error page handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404