name: Renovate
on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Renovate Config
        run: npx --package renovate -c 'renovate-config-validator'

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: debug 